export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";
export const GET_MAKEUPPRODUCT_REQUEST = "GET_MAKEUPPRODUCT_REQUEST";
export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";